-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Usr CASCADE;
DROP TABLE IF EXISTS Question CASCADE;
DROP TABLE IF EXISTS Answer CASCADE;
DROP TABLE IF EXISTS Membership CASCADE;
DROP TABLE IF EXISTS Organization CASCADE;
