-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Usr CASCADE;
DROP TABLE IF EXISTS Questions CASCADE;
DROP TABLE IF EXISTS Answers CASCADE;
DROP TABLE IF EXISTS Membership CASCADE;
DROP TABLE IF EXISTS Organization CASCADE;
